[build]
  base = "/"
  publish = "dist/portfolio/browser"
  command = "npm run ci:env && npm run build:ssg portfolio"
  ignore = "git diff --quiet $COMMIT_REF $CACHED_COMMIT_REF projects/portfolio"

[[redirects]]
  from = "https://joecocco.netlify.app/*"
  to = "https://joecocco.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
